### PR TITLE
Added step 1 install.ps1 to set copy always on the msi when the package is installed

### PR DESCRIPTION
**Pull request by nickfloyd**
This is the first step in https://newrelic.com/docs/dotnet/installing-the-net-agent-on-azure after installing the package.

### CODE REVIEW

**Comment by mikecousins** [comment]
I added some comments to the review.  I think we got some cruft into the nuspec file and the one path looks like a local path from your machine.

**Comment by mikecousins** [comment]
I just replied on GitHub, I don't know if that notified you or not.

---

From: Nick Floyd [reply@reply.github.com]
Sent: May 4, 2012 2:59 PM
To: Mike Cousins
Subject: [newrelicazurenuget] Added step 1 install.ps1 to set copy always on the msi when the package is installed (#5)

This is the first step in https://newrelic.com/docs/dotnet/installing-the-net-agent-on-azure after installing the package.

You can merge this Pull Request by running:

  git pull https://github.com/nickfloyd/newrelicazurenuget master

Or you can view, comment on it, or merge it online at:

  https://github.com/mikecousins/newrelicazurenuget/pull/5

-- Commit Summary --
- Added step 1 install.ps1 to set copy always on the msi when the package is installed

-- File Changes --

M NewRelicWindowsAzure.nuspec (22)
A tools/install.ps1 (4)

-- Patch Links --

  https://github.com/mikecousins/newrelicazurenuget/pull/5.patch
  https://github.com/mikecousins/newrelicazurenuget/pull/5.diff

---

Reply to this email directly or view it on GitHub:
https://github.com/mikecousins/newrelicazurenuget/pull/5

**Comment by nickfloyd** [comment]
Sorry about that totally my goof. I'll modify and resubmit the pull request.

**Comment by mikecousins** [comment]
No worries! I'm glad you're getting that in, it will be a great fix.

Nick Floyd reply@reply.github.com wrote:

Sorry about that totally my goof. I'll modify and resubmit the pull request.

---

**Pull request closed without merging**
